### ISSUE TITLE
Allow Projects/Categories to use the standard Hugo content

### ISSUE THREAD

**Issue by kellington** [digitalcraftsman/hugo-creative-theme#16]
I really like this theme.  And its 1 page simplicity. 
However, I wonder if it would be possible to allow a more detailed content page in markdown be developed that would be linked to from the model view?  Same for categories - each project has one but it doesn't link anywhere?

**Comment by digitalcraftsman** [comment]
Hi @kellington,

> However, I wonder if it would be possible to allow a more detailed content page in markdown be developed that would be linked to from the model view?

What do you mean with "model view"? Do you want to create a whole new page for the services or the categories?

> Same for categories - each project has one but it doesn't link anywhere?

The category links in the project modals are maybe obsolete but I left first of all them because they are part of the original. 

It would be great if you could clarify my questions from above :smiley: 

Cheers,
Digitalcraftsman

**Comment by digitalcraftsman** [comment]
Any updates here? Otherwise I'll close this issue.
